
#ifndef JAZZJACKRABBIT_PLAYER_COMMANDS_H
#define JAZZJACKRABBIT_PLAYER_COMMANDS_H

enum player_commands : uint8_t {
  MOVE_LEFT,
  MOVE_RIGHT,
  JUMP,
  STOP_MOVING,
  SHOOT,
  STOP_SHOOTING,
  CHANGE_WEAPON,
  SPECIAL_ATTACK,
};

#endif // JAZZJACKRABBIT_PLAYER_COMMANDS_H
